// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "My-Portfolio support"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/cryptocurrencies": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "все криптовалюты",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cryptocurrency"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "авторизация",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "parameters": [
                    {
                        "description": "data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.Tokens"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    }
                }
            }
        },
        "/api/v1/portfolio": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "портфель",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolio"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.PortfolioGetResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "добавить в портфель криптовалюту",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolio"
                ],
                "parameters": [
                    {
                        "description": "data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.PortfolioPostData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    }
                }
            }
        },
        "/api/v1/portfolio/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "удалить криптовалюту из портфеля",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolio"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Portfolio detail ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.PortfolioGetResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "обновитель информацию о криптовалюте в портфеле",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolio"
                ],
                "parameters": [
                    {
                        "description": "data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.PortfolioPatchData"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Portfolio detail ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    }
                }
            }
        },
        "/api/v1/refresh": {
            "post": {
                "description": "обновление токенов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "parameters": [
                    {
                        "description": "data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RefreshData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.Tokens"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    }
                }
            }
        },
        "/api/v1/register": {
            "post": {
                "description": "регистрация",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "parameters": [
                    {
                        "description": "data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RegisterData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controllers.Tokens"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    }
                }
            }
        },
        "/api/v1/stakings": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "список стейкингов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staking"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.StakingGetResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    }
                }
            }
        },
        "/api/v1/stakings/detail/{crypt_symbol}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "список стейкингов для конкретной криптовалюты",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staking"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cryptocurrency symbol",
                        "name": "crypt_symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.StakingDetailGetResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    }
                }
            }
        },
        "/api/v1/stakings/portfolio": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "список стейкингов для криптовалют в портфеле",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staking"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.StakingGetResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResponseError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "clients.CryptocurrencyDataDetail": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "quote": {
                    "type": "object",
                    "properties": {
                        "BTC": {
                            "type": "object",
                            "properties": {
                                "percent_change_24h": {
                                    "description": "Volume24h        float64 ` + "`" + `json:\"volume_24h\"` + "`" + `\nVolumeChange24h  float64 ` + "`" + `json:\"volume_change_24h\"` + "`" + `\nPercentChange1h  float64 ` + "`" + `json:\"percent_change_1h\"` + "`" + `",
                                    "type": "number"
                                },
                                "percent_change_30d": {
                                    "description": "PercentChange7d  float64 ` + "`" + `json:\"percent_change_7d\"` + "`" + `",
                                    "type": "number"
                                },
                                "percent_change_90d": {
                                    "description": "PercentChange60d float64 ` + "`" + `json:\"percent_change_60d\"` + "`" + `",
                                    "type": "number"
                                },
                                "price": {
                                    "type": "number"
                                }
                            }
                        },
                        "RUB": {
                            "type": "object",
                            "properties": {
                                "percent_change_24h": {
                                    "description": "Volume24h        float64 ` + "`" + `json:\"volume_24h\"` + "`" + `\nVolumeChange24h  float64 ` + "`" + `json:\"volume_change_24h\"` + "`" + `\nPercentChange1h  float64 ` + "`" + `json:\"percent_change_1h\"` + "`" + `",
                                    "type": "number"
                                },
                                "percent_change_30d": {
                                    "description": "PercentChange7d  float64 ` + "`" + `json:\"percent_change_7d\"` + "`" + `",
                                    "type": "number"
                                },
                                "percent_change_90d": {
                                    "description": "PercentChange60d float64 ` + "`" + `json:\"percent_change_60d\"` + "`" + `",
                                    "type": "number"
                                },
                                "price": {
                                    "type": "number"
                                }
                            }
                        },
                        "USD": {
                            "type": "object",
                            "properties": {
                                "percent_change_24h": {
                                    "description": "Volume24h        float64 ` + "`" + `json:\"volume_24h\"` + "`" + `\nVolumeChange24h  float64 ` + "`" + `json:\"volume_change_24h\"` + "`" + `\nPercentChange1h  float64 ` + "`" + `json:\"percent_change_1h\"` + "`" + `",
                                    "type": "number"
                                },
                                "percent_change_30d": {
                                    "description": "PercentChange7d  float64 ` + "`" + `json:\"percent_change_7d\"` + "`" + `",
                                    "type": "number"
                                },
                                "percent_change_90d": {
                                    "description": "PercentChange60d float64 ` + "`" + `json:\"percent_change_60d\"` + "`" + `",
                                    "type": "number"
                                },
                                "price": {
                                    "type": "number"
                                }
                            }
                        }
                    }
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "clients.StakingData": {
            "type": "object",
            "properties": {
                "apy": {
                    "type": "number"
                },
                "asset": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "quota_minimum": {
                    "type": "number"
                },
                "reward_asset": {
                    "type": "string"
                }
            }
        },
        "controllers.LoginData": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "controllers.PortfolioDetailGetResponse": {
            "type": "object",
            "properties": {
                "ROI": {
                    "type": "number"
                },
                "count": {
                    "type": "number"
                },
                "cryptocurrency": {
                    "type": "string"
                },
                "cryptocurrency_id": {
                    "type": "integer"
                },
                "cryptocurrency_symbol": {
                    "type": "string"
                },
                "now_price": {
                    "type": "number"
                },
                "percent_change_24h": {
                    "type": "number"
                },
                "percent_change_30d": {
                    "type": "number"
                },
                "percent_change_90d": {
                    "type": "number"
                },
                "portfolio_share": {
                    "type": "number"
                },
                "profit": {
                    "type": "number"
                },
                "purchases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.PurchaseGetResponse"
                    }
                },
                "sum": {
                    "type": "number"
                }
            }
        },
        "controllers.PortfolioGetResponse": {
            "type": "object",
            "properties": {
                "ROI": {
                    "type": "number"
                },
                "cryptocurrencies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.PortfolioDetailGetResponse"
                    }
                },
                "total_now_sum": {
                    "type": "number"
                },
                "total_purchased_sum": {
                    "type": "number"
                }
            }
        },
        "controllers.PortfolioPatchData": {
            "type": "object",
            "properties": {
                "commentary": {
                    "type": "string"
                },
                "count": {
                    "type": "number"
                },
                "price": {
                    "type": "number"
                },
                "purchase_time": {
                    "type": "string"
                }
            }
        },
        "controllers.PortfolioPostData": {
            "type": "object",
            "required": [
                "cmc_cryptocurrency_id",
                "count",
                "price",
                "purchase_time"
            ],
            "properties": {
                "cmc_cryptocurrency_id": {
                    "type": "integer"
                },
                "commentary": {
                    "type": "string"
                },
                "count": {
                    "type": "number"
                },
                "price": {
                    "type": "number"
                },
                "purchase_time": {
                    "type": "string"
                }
            }
        },
        "controllers.PurchaseGetResponse": {
            "type": "object",
            "required": [
                "count",
                "price",
                "purchase_time"
            ],
            "properties": {
                "commentary": {
                    "type": "string"
                },
                "count": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "purchase_time": {
                    "type": "string"
                },
                "sum": {
                    "type": "number"
                }
            }
        },
        "controllers.RefreshData": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "controllers.RegisterData": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 8
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "controllers.ResponseError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "error_string": {
                    "type": "string"
                }
            }
        },
        "controllers.ResponseSuccess": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "boolean"
                }
            }
        },
        "controllers.StakingDetailGetResponse": {
            "type": "object",
            "properties": {
                "binance_stakings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/clients.StakingData"
                    }
                },
                "bybit_stakings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/clients.StakingData"
                    }
                },
                "okx_stakings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/clients.StakingData"
                    }
                }
            }
        },
        "controllers.StakingGetResponse": {
            "type": "object",
            "properties": {
                "binance_staking": {
                    "$ref": "#/definitions/clients.StakingData"
                },
                "bybit_staking": {
                    "$ref": "#/definitions/clients.StakingData"
                },
                "cryptocurrency_data": {
                    "$ref": "#/definitions/clients.CryptocurrencyDataDetail"
                },
                "okx_staking": {
                    "$ref": "#/definitions/clients.StakingData"
                }
            }
        },
        "controllers.Tokens": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "My-Portfolio",
	Description:      "API for get cryptocurrencies",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
