definitions:
  clients.CryptocurrencyDataDetail:
    properties:
      id:
        type: integer
      name:
        type: string
      quote:
        properties:
          BTC:
            properties:
              percent_change_24h:
                description: |-
                  Volume24h        float64 `json:"volume_24h"`
                  VolumeChange24h  float64 `json:"volume_change_24h"`
                  PercentChange1h  float64 `json:"percent_change_1h"`
                type: number
              percent_change_30d:
                description: PercentChange7d  float64 `json:"percent_change_7d"`
                type: number
              percent_change_90d:
                description: PercentChange60d float64 `json:"percent_change_60d"`
                type: number
              price:
                type: number
            type: object
          RUB:
            properties:
              percent_change_24h:
                description: |-
                  Volume24h        float64 `json:"volume_24h"`
                  VolumeChange24h  float64 `json:"volume_change_24h"`
                  PercentChange1h  float64 `json:"percent_change_1h"`
                type: number
              percent_change_30d:
                description: PercentChange7d  float64 `json:"percent_change_7d"`
                type: number
              percent_change_90d:
                description: PercentChange60d float64 `json:"percent_change_60d"`
                type: number
              price:
                type: number
            type: object
          USD:
            properties:
              percent_change_24h:
                description: |-
                  Volume24h        float64 `json:"volume_24h"`
                  VolumeChange24h  float64 `json:"volume_change_24h"`
                  PercentChange1h  float64 `json:"percent_change_1h"`
                type: number
              percent_change_30d:
                description: PercentChange7d  float64 `json:"percent_change_7d"`
                type: number
              percent_change_90d:
                description: PercentChange60d float64 `json:"percent_change_60d"`
                type: number
              price:
                type: number
            type: object
        type: object
      symbol:
        type: string
    type: object
  clients.StakingData:
    properties:
      apy:
        type: number
      asset:
        type: string
      duration:
        type: integer
      quota_minimum:
        type: number
      reward_asset:
        type: string
    type: object
  controllers.LoginData:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controllers.PortfolioDetailGetResponse:
    properties:
      ROI:
        type: number
      count:
        type: number
      cryptocurrency:
        type: string
      cryptocurrency_id:
        type: integer
      cryptocurrency_symbol:
        type: string
      now_price:
        type: number
      percent_change_24h:
        type: number
      percent_change_30d:
        type: number
      percent_change_90d:
        type: number
      portfolio_share:
        type: number
      profit:
        type: number
      purchases:
        items:
          $ref: '#/definitions/controllers.PurchaseGetResponse'
        type: array
      sum:
        type: number
    type: object
  controllers.PortfolioGetResponse:
    properties:
      ROI:
        type: number
      cryptocurrencies:
        items:
          $ref: '#/definitions/controllers.PortfolioDetailGetResponse'
        type: array
      total_now_sum:
        type: number
      total_purchased_sum:
        type: number
    type: object
  controllers.PortfolioPatchData:
    properties:
      commentary:
        type: string
      count:
        type: number
      price:
        type: number
      purchase_time:
        type: string
    type: object
  controllers.PortfolioPostData:
    properties:
      cmc_cryptocurrency_id:
        type: integer
      commentary:
        type: string
      count:
        type: number
      price:
        type: number
      purchase_time:
        type: string
    required:
    - cmc_cryptocurrency_id
    - count
    - price
    - purchase_time
    type: object
  controllers.PurchaseGetResponse:
    properties:
      commentary:
        type: string
      count:
        type: number
      created_at:
        type: string
      id:
        type: string
      price:
        type: number
      purchase_time:
        type: string
      sum:
        type: number
    required:
    - count
    - price
    - purchase_time
    type: object
  controllers.RefreshData:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  controllers.RegisterData:
    properties:
      password:
        maxLength: 20
        minLength: 8
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controllers.ResponseError:
    properties:
      error:
        type: boolean
      error_string:
        type: string
    type: object
  controllers.ResponseSuccess:
    properties:
      data: {}
      error:
        type: boolean
    type: object
  controllers.StakingDetailGetResponse:
    properties:
      binance_stakings:
        items:
          $ref: '#/definitions/clients.StakingData'
        type: array
      bybit_stakings:
        items:
          $ref: '#/definitions/clients.StakingData'
        type: array
      okx_stakings:
        items:
          $ref: '#/definitions/clients.StakingData'
        type: array
    type: object
  controllers.StakingGetResponse:
    properties:
      binance_staking:
        $ref: '#/definitions/clients.StakingData'
      bybit_staking:
        $ref: '#/definitions/clients.StakingData'
      cryptocurrency_data:
        $ref: '#/definitions/clients.CryptocurrencyDataDetail'
      okx_staking:
        $ref: '#/definitions/clients.StakingData'
    type: object
  controllers.Tokens:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user_id:
        type: string
      username:
        type: string
    type: object
host: 127.0.0.1:8000
info:
  contact:
    name: My-Portfolio support
  description: API for get cryptocurrencies
  title: My-Portfolio
  version: "1.0"
paths:
  /api/v1/cryptocurrencies:
    get:
      consumes:
      - application/json
      description: все криптовалюты
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ResponseSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ResponseError'
      security:
      - ApiKeyAuth: []
      tags:
      - cryptocurrency
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: авторизация
      parameters:
      - description: data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Tokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ResponseError'
      tags:
      - auth
  /api/v1/portfolio:
    get:
      consumes:
      - application/json
      description: портфель
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.PortfolioGetResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ResponseError'
      security:
      - ApiKeyAuth: []
      tags:
      - portfolio
    post:
      consumes:
      - application/json
      description: добавить в портфель криптовалюту
      parameters:
      - description: data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.PortfolioPostData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ResponseSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ResponseError'
      security:
      - ApiKeyAuth: []
      tags:
      - portfolio
  /api/v1/portfolio/{id}:
    delete:
      consumes:
      - application/json
      description: удалить криптовалюту из портфеля
      parameters:
      - description: Portfolio detail ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.PortfolioGetResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ResponseError'
      security:
      - ApiKeyAuth: []
      tags:
      - portfolio
    patch:
      consumes:
      - application/json
      description: обновитель информацию о криптовалюте в портфеле
      parameters:
      - description: data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.PortfolioPatchData'
      - description: Portfolio detail ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ResponseSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ResponseError'
      security:
      - ApiKeyAuth: []
      tags:
      - portfolio
  /api/v1/refresh:
    post:
      consumes:
      - application/json
      description: обновление токенов
      parameters:
      - description: data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.RefreshData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Tokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ResponseError'
      tags:
      - auth
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: регистрация
      parameters:
      - description: data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterData'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.Tokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ResponseError'
      tags:
      - auth
  /api/v1/stakings:
    get:
      consumes:
      - application/json
      description: список стейкингов
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.StakingGetResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ResponseError'
      security:
      - ApiKeyAuth: []
      tags:
      - staking
  /api/v1/stakings/detail/{crypt_symbol}:
    get:
      consumes:
      - application/json
      description: список стейкингов для конкретной криптовалюты
      parameters:
      - description: Cryptocurrency symbol
        in: path
        name: crypt_symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.StakingDetailGetResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ResponseError'
      security:
      - ApiKeyAuth: []
      tags:
      - staking
  /api/v1/stakings/portfolio:
    get:
      consumes:
      - application/json
      description: список стейкингов для криптовалют в портфеле
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.StakingGetResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ResponseError'
      security:
      - ApiKeyAuth: []
      tags:
      - staking
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
